"""Archive library, automation, secure profiles, options, and runtime UI."""

from __future__ import annotations

import json
import os
import re
import stat
import sys
import time
import uuid
from difflib import get_close_matches
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from PySide6.QtCore import QProcess, QTime, QTimer, Qt, QUrl
from PySide6.QtGui import QAction, QTextCursor
from PySide6.QtNetwork import QNetworkAccessManager, QNetworkProxy, QNetworkReply, QNetworkRequest
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QDialog,
    QFileDialog,
    QFormLayout,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMenu,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSpinBox,
    QStackedWidget,
    QTabWidget,
    QTableWidget,
    QTableWidgetItem,
    QTimeEdit,
    QVBoxLayout,
    QWidget,
)
from shiboken6 import isValid

from .core import (
    APP_DIR,
    MANAGED_AUTH_KEYS,
    OAuthOutputRedactor,
    REDACTED,
    append_extra_args_to_database_text,
    atomic_write_text,
    command_string_to_argv,
    is_sensitive_option_key,
    parse_text_database,
    quote_arg_for_preview,
    read_text_safely,
    redact_oauth_output as redact_oauth_output,
    redact_sensitive_database_text,
    redact_sensitive_text,
    safe_int,
    validate_cookies_txt,
)
from .feature_logic import build_filter_expression, next_schedule_time, parse_help_options
from .feature_store import FeatureStore
from .secure_vault import SecretVault
from .oauth_flow import local_oauth_callback_url, oauth_flow_guidance


SECURE_RUNTIME_DIR = APP_DIR / "runtime"
MANAGED_VENV_DIR = SECURE_RUNTIME_DIR / "gallery-dl-venv"
ACCOUNT_CACHE_DIR = APP_DIR / "account-cache"

# Authentication methods documented by gallery-dl.  The account editor also
# lists every extractor category installed locally for cookie/API profiles,
# but these allowlists keep the guided OAuth/password flows typo-free.
OAUTH_SITES = (
    "pixiv",
    "deviantart",
    "flickr",
    "reddit",
    "smugmug",
    "tumblr",
    "mastodon",
)
USERNAME_PASSWORD_SITES = (
    "nijie",
    "aryion",
    "danbooru",
    "e621",
    "idolcomplex",
    "imgbb",
    "inkbunny",
    "mangadex",
    "mangoxo",
    "pillowfort",
    "sankaku",
    "subscribestar",
    "tapas",
    "tsumino",
    "zerochan",
)
ACCOUNT_AUTH_LABELS = {
    "browser": "Browser cookies",
    "cookies_file": "cookies.txt",
    "username_password": "Username + password",
    "api_key": "API key / token",
    "oauth": "OAuth",
}


def installed_extractor_categories() -> list[str]:
    """Return installed gallery-dl categories, with a safe documented fallback."""
    categories = set(OAUTH_SITES) | set(USERNAME_PASSWORD_SITES)
    try:
        from gallery_dl import extractor

        categories.update(
            str(item.category).strip().lower()
            for item in extractor.extractors()
            if str(getattr(item, "category", "")).strip()
        )
    except Exception:
        # The account UI remains usable while gallery-dl is being repaired or
        # when its internal extractor catalog changes in a future release.
        pass
    return sorted(categories)


def account_site_error(value: str, catalog: list[str] | tuple[str, ...]) -> str:
    """Explain an invalid extractor category and suggest the nearest match."""
    site = str(value or "").strip().lower()
    choices = sorted({str(item).strip().lower() for item in catalog if str(item).strip()})
    if not site:
        return "Choose a site from the installed extractor list."
    if site in choices:
        return ""
    matches = get_close_matches(site, choices, n=3, cutoff=0.55)
    suggestion = f" Did you mean: {', '.join(matches)}?" if matches else ""
    return f"Unknown gallery-dl site/extractor '{site}'.{suggestion}"


def browser_cookie_source(browser: str, profile: str = "", domain: str = "") -> str:
    """Build gallery-dl's BROWSER[/DOMAIN][:PROFILE] cookie source syntax."""
    name = str(browser or "").strip().lower()
    if not name or any(char.isspace() for char in name) or any(
        char in name for char in ("\\", "/", ":")
    ):
        raise ValueError("Choose a valid browser name")
    domain_value = str(domain or "").strip().strip()
    profile_value = str(profile or "").strip()
    if any(char in domain_value for char in "\r\n:"):
        raise ValueError("Cookie domain cannot contain a colon or a new line")
    if any(char in profile_value for char in "\r\n"):
        raise ValueError("Browser profile cannot contain a new line")
    source = name
    if domain_value:
        source += "/" + domain_value
    if profile_value:
        source += ":" + profile_value
    return source


def split_browser_cookie_source(source: str) -> tuple[str, str, str]:
    """Read the subset of browser-cookie syntax generated by this account UI."""
    value = str(source or "").strip()
    browser_and_domain, separator, profile = value.partition(":")
    browser, slash, domain = browser_and_domain.partition("/")
    return browser.lower(), profile if separator else "", domain if slash else ""


def default_account_cache_path(site: str) -> str:
    """Create a collision-resistant cache filename owned by one account profile."""
    safe_site = re.sub(r"[^a-z0-9_.-]+", "-", str(site or "account").lower()).strip("-.")
    safe_site = safe_site or "account"
    return str(ACCOUNT_CACHE_DIR / f"{safe_site}-{uuid.uuid4().hex}.sqlite3")


def oauth_target(site: str, instance: str = "") -> str:
    """Build and validate gallery-dl's documented OAuth pseudo-URL."""
    category = str(site or "").strip().lower()
    if category not in OAUTH_SITES:
        raise ValueError(f"{category or 'This site'} does not support OAuth in gallery-dl")
    instance_value = str(instance or "").strip()
    if category != "mastodon":
        if instance_value:
            raise ValueError("An OAuth instance is only used for Mastodon")
        return f"oauth:{category}"
    if not instance_value:
        raise ValueError("Enter the Mastodon instance, for example mastodon.social")
    parsed = urlparse(instance_value if "://" in instance_value else "//" + instance_value)
    if not parsed.hostname or any(char.isspace() for char in instance_value):
        raise ValueError("Enter a valid Mastodon instance hostname or https URL")
    return f"oauth:mastodon:{instance_value}"


def account_action_argv(
    gdl_cmd: str,
    action: str,
    *,
    site: str,
    cache_file: str,
    oauth_instance: str = "",
    config_path: str = "",
) -> list[str]:
    """Build argv for account OAuth and cache-management actions."""
    base = command_string_to_argv(gdl_cmd or "gallery-dl") or ["gallery-dl"]
    argv = list(base)
    if config_path:
        argv.extend(["--config", str(config_path)])
    cache = str(cache_file or "").strip()
    if not cache:
        raise ValueError("The account profile has no private cache path")
    argv.extend(["--cache-file", cache])
    if action == "oauth":
        # QProcess stdin is a pipe rather than a TTY. gallery-dl otherwise
        # refuses Pixiv's input("code: ") prompt before the GUI can send it.
        argv.extend(["-o", "extractor.input=true", oauth_target(site, oauth_instance)])
    elif action == "status":
        argv.append("--cache-status")
    elif action == "show":
        argv.extend(["--cache-show", str(site).strip().lower()])
    elif action == "clear_site":
        argv.extend(["--cache-clear", str(site).strip().lower()])
    elif action == "clear_all":
        argv.extend(["--cache-clear", "ALL"])
    elif action == "clear_expired":
        argv.extend(["--cache-clear", "EXP"])
    elif action == "vacuum":
        argv.append("--cache-vacuum")
    else:
        raise ValueError(f"Unsupported account action: {action}")
    return argv


def normalize_clipboard_url_candidate(value: str) -> str:
    """Trim prose punctuation without corrupting balanced URL parentheses."""
    url = str(value or "").rstrip(".,;")
    pairs = {")": "(", "]": "[", "}": "{"}
    while url and url[-1] in pairs:
        closing = url[-1]
        opening = pairs[closing]
        if url.count(closing) <= url.count(opening):
            break
        url = url[:-1]
    return url


def interrupted_recovery_commands(rows: list[dict[str, object]]) -> list[str]:
    """Keep one recovery command per unfinished run item, including duplicates."""
    return [
        str(row.get("command") or "").strip()
        for row in rows
        if str(row.get("command") or "").strip()
    ]


def library_records_to_database_text(rows: list[dict[str, object]]) -> str:
    """Serialize library selections without losing their sticky tag metadata."""
    lines: list[str] = []
    last_tag = ""
    for row in rows:
        tag = " ".join(str(row.get("tag") or "").split())
        if tag != last_tag:
            lines.append(f"# {tag}" if tag else "#")
            last_tag = tag
        command = str(row.get("command") or row.get("url") or "").strip()
        if command:
            lines.append(command)
    return "\n".join(lines)


def common_account_profile_id(rows: list[dict[str, object]]) -> int | None:
    """Return one shared account id; mixed/public selections use no profile."""
    profile_ids = {
        safe_int(row.get("account_profile_id"), 0, 0) or None
        for row in rows
    }
    if len(profile_ids) != 1:
        return None
    return profile_ids.pop()


def format_schedule_timestamp(value: object) -> str:
    """Format persisted schedule timestamps without trusting database values."""
    try:
        return datetime.fromtimestamp(float(value)).strftime("%Y-%m-%d %H:%M")
    except (TypeError, ValueError, OSError, OverflowError):
        return "Invalid timestamp"


class ManagementMixin:
    """Feature center and lifecycle services mixed into :class:`MainWindow`."""

    def _initialize_management_state(self) -> None:
        self.feature_store = FeatureStore()
        self.feature_store.migrate_jsonl_history()
        self.secret_vault = SecretVault()
        self.current_run_id: int | None = None
        self._run_config_path: str | None = None
        self.active_account_profile_id: int | None = None
        self.clipboard_inbox_enabled = False
        self.clipboard_allowed_hosts = ""
        self.close_to_tray = False
        self._force_quit = False
        self._last_clipboard_text = ""
        self._management_dialog: QDialog | None = None
        self._runtime_process: QProcess | None = None
        self._runtime_stage = ""
        # A due schedule temporarily owns the visible queue while its workers
        # run. Preserve the user's manually prepared queue and restore it after
        # the scheduled run (or immediately when dispatch fails) so automation
        # never replaces unrelated work in the editor/autosave.
        self._scheduled_queue_restore: str | None = None

    def _start_management_services(self) -> None:
        self._cleanup_stale_secure_configs()
        recovered_db = getattr(self.feature_store, "recovered_corrupt_path", None)
        if recovered_db is not None:
            self.append_log(
                f"[database] corrupt library database preserved as: {recovered_db}"
            )
            QTimer.singleShot(
                0,
                lambda: self.show_compact_message(
                    "Library database recovered",
                    "The library database was corrupt and could not be opened. "
                    "It was preserved for recovery and a clean database was created:\n"
                    f"{recovered_db}",
                    "warning",
                ),
            )
        clipboard = QApplication.clipboard()
        clipboard.dataChanged.connect(self._on_clipboard_changed)
        self.schedule_timer = QTimer(self)
        self.schedule_timer.timeout.connect(self._poll_schedules)
        self.schedule_timer.start(30_000)
        if self.close_to_tray:
            self._ensure_persistent_tray()
        QTimer.singleShot(600, self._offer_crash_recovery)

    # ------------------------------------------------------------------ lifecycle
    def _offer_crash_recovery(self) -> None:
        if self.active_workers > 0:
            return
        interrupted = self.feature_store.interrupted_runs()
        if not interrupted:
            return
        commands = interrupted_recovery_commands(interrupted)
        run_ids: set[int] = set()
        for row in interrupted:
            run_ids.add(int(row["run_id"]))
        if not commands:
            self.feature_store.resolve_interrupted_runs(run_ids)
            return
        answer = QMessageBox.question(
            self,
            "Interrupted download",
            f"The previous session ended while {len(commands)} job(s) were unfinished.\n\n"
            "Load and resume them now?",
        )
        if answer == QMessageBox.Yes:
            self.txt_commands.setPlainText("\n".join(commands))
            # Resolve only after the recovery queue is safely visible. If the
            # dialog or widget update fails (or the process dies while the
            # prompt is open), the prior run remains recoverable next launch.
            self.feature_store.resolve_interrupted_runs(run_ids)
            if any(REDACTED in command for command in commands):
                QMessageBox.information(
                    self,
                    "Interrupted download",
                    "Inline credentials were removed from the recovery record. "
                    "Review the loaded commands and re-enter authentication before starting.",
                )
            else:
                QTimer.singleShot(
                    0,
                    lambda: self._start_download_now(run_source="recovery"),
                )
        else:
            self.feature_store.resolve_interrupted_runs(run_ids)

    def _ensure_persistent_tray(self) -> None:
        if self.tray_icon is None:
            from PySide6.QtWidgets import QStyle, QSystemTrayIcon

            self.tray_icon = QSystemTrayIcon(self)
            icon = self.windowIcon()
            if icon.isNull():
                icon = self.style().standardIcon(QStyle.SP_ComputerIcon)
            self.tray_icon.setIcon(icon)
            menu = QMenu(self)
            show_action = QAction("Open GdlScrape", self)
            show_action.triggered.connect(self._restore_from_tray)
            quit_action = QAction("Exit", self)
            quit_action.triggered.connect(self._quit_from_tray)
            menu.addAction(show_action)
            menu.addSeparator()
            menu.addAction(quit_action)
            self.tray_icon.setContextMenu(menu)
            self.tray_icon.activated.connect(
                lambda reason: self._restore_from_tray()
                if reason == QSystemTrayIcon.DoubleClick
                else None
            )
        self.tray_icon.show()

    def _restore_from_tray(self) -> None:
        self.show()
        self.raise_()
        self.activateWindow()

    def _quit_from_tray(self) -> None:
        self._force_quit = True
        self.close()

    # ------------------------------------------------------------------ clipboard
    def _on_clipboard_changed(self) -> None:
        if not self.clipboard_inbox_enabled or self.active_workers > 0:
            return
        text = QApplication.clipboard().text().strip()
        if not text or text == self._last_clipboard_text or len(text) > 65_536:
            return
        self._last_clipboard_text = text
        allowed = {
            host.strip().lower()
            for host in self.clipboard_allowed_hosts.split(",")
            if host.strip()
        }
        candidates: list[str] = []
        for match in re.findall(r"https?://[^\s<>\"']+", text)[:50]:
            url = normalize_clipboard_url_candidate(match)
            try:
                parsed = urlparse(url)
                hostname = parsed.hostname
            except ValueError:
                # urllib rejects unmatched IPv6 brackets. Clipboard contents
                # are untrusted prose, so one malformed candidate must not
                # escape the Qt callback and disable inbox processing.
                continue
            if (
                parsed.scheme not in {"http", "https"}
                or not hostname
                or parsed.username is not None
                or parsed.password is not None
            ):
                continue
            host = hostname.lower()
            if allowed and not any(host == item or host.endswith("." + item) for item in allowed):
                continue
            if url not in candidates:
                candidates.append(url)
        if not candidates:
            return
        try:
            existing = {
                job.url for job in parse_text_database(self.txt_commands.toPlainText())
            }
        except ValueError as exc:
            # Clipboard signals run inside Qt's event loop. A queue that is
            # already oversized/malformed must not turn a harmless clipboard
            # change into an uncaught callback exception. Allow the same URL to
            # be retried after the user fixes the queue and copies it again.
            self._last_clipboard_text = ""
            self.append_log(f"[clipboard inbox] current queue could not be parsed: {exc}")
            return
        additions = [url for url in candidates if url not in existing]
        if not additions:
            return
        current = self.txt_commands.toPlainText().rstrip()
        self.txt_commands.setPlainText((current + "\n" if current else "") + "\n".join(additions))
        self.append_log(f"[clipboard inbox] added {len(additions)} URL(s)")
        self.statusBar().showMessage(f"Clipboard Inbox added {len(additions)} URL(s)", 4000)

    # ------------------------------------------------------------------ scheduler
    def _restore_queue_after_scheduled_run(self) -> bool:
        """Restore queue text temporarily replaced by a scheduler dispatch."""
        previous = self._scheduled_queue_restore
        if previous is None:
            return False
        self._scheduled_queue_restore = None
        self.txt_commands.setPlainText(previous)
        # Keep the queue model/table aligned with the restored editor before an
        # autosave or another scheduled poll can observe it.
        self._rebuild_from_text()
        self.append_log("[scheduler] restored the previous manual queue")
        return True

    def _poll_schedules(self) -> None:
        if self.active_workers > 0 or (self.delay_timer and self.delay_timer.isActive()):
            return
        due = self.feature_store.due_schedules()
        if not due:
            return
        schedule = due[0]
        command_text = str(schedule.get("command_text") or "").strip()
        schedule_id = int(schedule["id"])
        if REDACTED in command_text:
            # Old databases may contain schedules created before redacted
            # commands were forced disabled. They can never run: the queue
            # safety gate rejects the placeholder before account config is
            # prepared. Disable them once instead of retrying every five
            # minutes forever.
            self.feature_store.set_schedule_enabled(schedule_id, False)
            self.append_log(
                f"[scheduler] disabled schedule with removed credentials: "
                f"{schedule.get('name')}"
            )
            return
        next_run = next_schedule_time(schedule)
        if not command_text:
            self.feature_store.advance_schedule(schedule_id, next_run)
            self.append_log(f"[scheduler] skipped empty schedule: {schedule.get('name')}")
            return
        raw_account_id = schedule.get("account_profile_id")
        account_id = safe_int(raw_account_id, 0, 0) or None
        if raw_account_id not in (None, "") and account_id is None:
            self.feature_store.defer_schedule(schedule_id, time.time() + 5 * 60)
            self.append_log(
                f"[scheduler] invalid account profile for {schedule.get('name')}; "
                "retrying in 5 minutes"
            )
            return
        self._scheduled_queue_restore = self.txt_commands.toPlainText()
        self.txt_commands.setPlainText(command_text)
        self.append_log(f"[scheduler] starting: {schedule.get('name')}")
        try:
            started = self._start_download_now(
                run_source=f"schedule:{schedule_id}",
                account_profile_id=account_id,
                use_account_override=True,
            )
        except Exception as exc:
            # A Qt timer callback must not leak an exception into the event
            # loop. If workers became active before a later UI update failed,
            # retain the scheduled queue and treat the dispatch as started;
            # otherwise preserve the user's queue and retry shortly.
            started = self.active_workers > 0
            state = "workers are active" if started else "no workers became active"
            self.append_log(
                f"[scheduler] unexpected start error for {schedule.get('name')} "
                f"({state}): {exc}"
            )
        if started:
            self.feature_store.advance_schedule(schedule_id, next_run)
        else:
            self._restore_queue_after_scheduled_run()
            retry_at = time.time() + 5 * 60
            self.feature_store.defer_schedule(schedule_id, retry_at)
            self.append_log(
                f"[scheduler] start failed; retrying in 5 minutes: {schedule.get('name')}"
            )

    # ------------------------------------------------------------ secure profiles
    def prepare_active_account_config(
        self,
        account_profile_id: int | None = None,
        *,
        use_active_default: bool = True,
    ) -> str | None:
        """Create a short-lived merged config for the selected account profile."""
        self.cleanup_run_account_config()
        selected_account_id = (
            self.active_account_profile_id if use_active_default else account_profile_id
        )
        profile = self.feature_store.account(selected_account_id)
        if selected_account_id and not profile:
            raise RuntimeError(
                f"The selected account profile no longer exists: {selected_account_id}"
            )
        if not profile:
            return None
        base: dict[str, object] = {}
        active_config = Path(self.config_path).expanduser() if self.config_path else None
        if active_config and active_config.is_file():
            try:
                loaded = json.loads(read_text_safely(active_config))
            except (OSError, ValueError) as exc:
                raise RuntimeError(f"Active config cannot be merged with the account profile: {exc}") from exc
            if not isinstance(loaded, dict):
                raise RuntimeError("Active config must contain a JSON object")
            base = loaded
        extractor = base.setdefault("extractor", {})
        if not isinstance(extractor, dict):
            raise RuntimeError("The active config extractor section must be a JSON object")
        site = str(profile.get("site") or "").strip().lower()
        site_config = extractor.setdefault(site, {})
        if not isinstance(site_config, dict):
            raise RuntimeError(f"Config extractor.{site} must be a JSON object")
        auth_kind = str(profile.get("auth_kind") or "browser")
        cache_file = str(profile.get("cache_file") or "").strip()
        if cache_file:
            cache = base.setdefault("cache", {})
            if not isinstance(cache, dict):
                raise RuntimeError("The active config cache section must be a JSON object")
            cache["file"] = cache_file
        elif auth_kind == "oauth":
            raise RuntimeError("The selected OAuth profile has no private cache path")
        auth_keys = set(MANAGED_AUTH_KEYS)
        auth_keys.add(str(profile.get("secret_key") or "api-key"))
        for key in list(site_config):
            if key in auth_keys or is_sensitive_option_key(key):
                site_config.pop(key, None)
        if auth_kind == "browser":
            source = str(profile.get("cookie_source") or "chrome")
            site_config["cookies"] = [source]
        elif auth_kind == "cookies_file":
            source = str(profile.get("cookie_source") or "")
            if not source:
                raise RuntimeError("The selected cookies.txt profile has no file path")
            cookie_path = Path(source).expanduser()
            if not cookie_path.is_file():
                raise RuntimeError(f"The selected cookies.txt file does not exist: {cookie_path}")
            site_config["cookies"] = str(cookie_path)
        elif auth_kind == "oauth":
            # OAuth tokens and sessions are resolved from this profile's
            # isolated gallery-dl cache.  They are never copied into config.
            pass
        else:
            secret = self.secret_vault.get(str(profile.get("secret_ref") or ""))
            if not secret:
                raise RuntimeError("The selected account secret is unavailable")
            username = str(profile.get("username") or "")
            if auth_kind == "username_password":
                site_config["username"] = username
                site_config["password"] = secret
            elif auth_kind == "api_key":
                site_config[str(profile.get("secret_key") or "api-key")] = secret
            else:
                raise RuntimeError(f"Unsupported account authentication method: {auth_kind}")
        SECURE_RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
        path = SECURE_RUNTIME_DIR / f"secure-config-{uuid.uuid4().hex}.json"
        atomic_write_text(
            path,
            json.dumps(base, ensure_ascii=False, indent=2),
            encoding="utf-8",
            mode=stat.S_IRUSR | stat.S_IWUSR,
        )
        self._run_config_path = str(path)
        return self._run_config_path

    def cleanup_run_account_config(self) -> None:
        path = getattr(self, "_run_config_path", None)
        self._run_config_path = None
        if path:
            try:
                Path(path).unlink(missing_ok=True)
            except OSError:
                pass

    def _cleanup_stale_secure_configs(self) -> None:
        if not SECURE_RUNTIME_DIR.exists():
            return
        for path in SECURE_RUNTIME_DIR.glob("secure-config-*.json"):
            try:
                path.unlink()
            except OSError:
                pass

    # ---------------------------------------------------------------- dialog shell
    def open_management_center(self) -> None:
        if self._management_dialog is not None and self._management_dialog.isVisible():
            self._management_dialog.raise_()
            self._management_dialog.activateWindow()
            return
        dialog = QDialog(self)
        dialog.setWindowTitle("Library & Automation Center")
        dialog.resize(980, 700)
        dialog.setMinimumSize(820, 600)
        root = QVBoxLayout(dialog)
        intro = QLabel(
            "Persistent archive library, recurring schedules, Clipboard Inbox, secure account profiles, "
            + ("installed-version options, and the included gallery-dl." if getattr(sys, "frozen", False)
               else "installed-version options, and an isolated gallery-dl runtime.")
        )
        intro.setWordWrap(True)
        intro.setObjectName("subtle")
        root.addWidget(intro)
        tabs = QTabWidget()
        root.addWidget(tabs, 1)
        tabs.addTab(self._build_library_tab(), "Library")
        tabs.addTab(self._build_scheduler_tab(), "Scheduler")
        tabs.addTab(self._build_inbox_tab(), "URL Inbox")
        tabs.addTab(self._build_accounts_tab(), "Accounts")
        tabs.addTab(self._build_options_tab(), "Options & Filters")
        tabs.addTab(self._build_runtime_tab(), "Runtime")
        close = QPushButton("Close")
        close.clicked.connect(dialog.accept)
        root.addWidget(close, 0, Qt.AlignRight)
        self._management_dialog = dialog
        dialog.finished.connect(lambda _result: setattr(self, "_management_dialog", None))
        dialog.show()

    @staticmethod
    def _table(columns: list[str]) -> QTableWidget:
        table = QTableWidget(0, len(columns))
        table.setHorizontalHeaderLabels(columns)
        table.setSelectionBehavior(QTableWidget.SelectRows)
        table.setEditTriggers(QTableWidget.NoEditTriggers)
        table.verticalHeader().setVisible(False)
        table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        table.horizontalHeader().setStretchLastSection(True)
        return table

    # --------------------------------------------------------------------- library
    def _build_library_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        toolbar = QHBoxLayout()
        search = QLineEdit()
        search.setPlaceholderText("Search title, URL, service, or tag")
        import_current = QPushButton("Import Current Queue")
        queue_selected = QPushButton("Queue Selected")
        delete_selected = QPushButton("Delete Selected")
        toolbar.addWidget(search, 1)
        toolbar.addWidget(import_current)
        toolbar.addWidget(queue_selected)
        toolbar.addWidget(delete_selected)
        layout.addLayout(toolbar)
        table = self._table(["ID", "Title", "Service", "Tag", "Last status", "New files", "URL"])
        layout.addWidget(table, 1)

        def refresh() -> None:
            rows = self.feature_store.list_library(search.text())
            table.setRowCount(len(rows))
            for row_index, record in enumerate(rows):
                values = [
                    record["id"], record["title"], record["service"], record["tag"],
                    record["last_status"], record["last_downloaded"], record["url"],
                ]
                for column, value in enumerate(values):
                    table.setItem(row_index, column, QTableWidgetItem(str(value)))

        def import_queue() -> None:
            if not self._rebuild_from_text():
                return
            redacted_count = sum(
                redact_sensitive_text(job.raw) != job.raw for job in self.jobs
            )
            for job in self.jobs:
                self.feature_store.add_library_entry(
                    url=job.url,
                    title=job.ident if job.ident != "-" else "",
                    service=job.service,
                    tag=job.tag,
                    output_dir=job.dest if job.dest != "-" else "",
                    account_profile_id=self.active_account_profile_id,
                    command=job.raw,
                )
            refresh()
            self.append_log(f"[library] imported {len(self.jobs)} current job(s)")
            if redacted_count:
                QMessageBox.warning(
                    page,
                    "Library credentials removed",
                    f"Inline credentials were removed from {redacted_count} stored command(s). "
                    "Use an Account profile or saved cookies when queueing them again.",
                )

        def selected_ids() -> list[int]:
            return sorted({int(table.item(index.row(), 0).text()) for index in table.selectedIndexes()})

        def queue_rows() -> None:
            if self.active_workers > 0:
                QMessageBox.information(page, "Library", "Wait for the current download to finish before replacing the queue.")
                return
            selected = set(selected_ids())
            records = [row for row in self.feature_store.list_library(search.text()) if int(row["id"]) in selected]
            if not records:
                return
            self.txt_commands.setPlainText(library_records_to_database_text(records))
            self.active_account_profile_id = common_account_profile_id(records)
            if not self._rebuild_from_text():
                return
            if self._management_dialog is not None:
                self._management_dialog.accept()

        import_current.clicked.connect(import_queue)
        queue_selected.clicked.connect(queue_rows)
        def delete_rows() -> None:
            self.feature_store.delete_library_entries(selected_ids())
            refresh()

        delete_selected.clicked.connect(delete_rows)
        search.textChanged.connect(refresh)
        refresh()
        return page

    # ------------------------------------------------------------------- schedules
    def _build_scheduler_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        table = self._table(["ID", "Enabled", "Name", "Frequency", "Next run", "Account", "Commands"])
        table.setMaximumHeight(250)
        layout.addWidget(table)
        form = QGridLayout()
        name = QLineEdit("Daily archive check")
        frequency = QComboBox()
        frequency.addItems(["interval", "daily", "weekly"])
        interval = QSpinBox()
        interval.setRange(1, 10080)
        interval.setValue(60)
        interval.setSuffix(" min")
        run_time = QTimeEdit(QTime(2, 0))
        run_time.setDisplayFormat("HH:mm")
        weekdays = QLineEdit("0,1,2,3,4,5,6")
        weekdays.setToolTip("Monday=0 through Sunday=6; used only for weekly schedules.")
        enabled = QCheckBox("Enabled")
        enabled.setChecked(True)
        account = QComboBox()
        account.addItem("No account profile", None)
        for record in self.feature_store.list_accounts():
            account.addItem(str(record["name"]), int(record["id"]))
        commands = QPlainTextEdit(self.txt_commands.toPlainText())
        commands.setPlaceholderText("One URL or gallery-dl command per line")
        commands.setMinimumHeight(130)
        form.addWidget(QLabel("Name"), 0, 0)
        form.addWidget(name, 0, 1)
        form.addWidget(QLabel("Frequency"), 0, 2)
        form.addWidget(frequency, 0, 3)
        form.addWidget(QLabel("Interval"), 1, 0)
        form.addWidget(interval, 1, 1)
        form.addWidget(QLabel("Time"), 1, 2)
        form.addWidget(run_time, 1, 3)
        form.addWidget(QLabel("Weekdays"), 2, 0)
        form.addWidget(weekdays, 2, 1, 1, 2)
        form.addWidget(enabled, 2, 3)
        form.addWidget(QLabel("Account profile"), 3, 0)
        form.addWidget(account, 3, 1, 1, 3)
        form.addWidget(QLabel("Queue snapshot"), 4, 0)
        form.addWidget(commands, 4, 1, 1, 3)
        layout.addLayout(form)
        buttons = QHBoxLayout()
        new_button = QPushButton("New")
        save_button = QPushButton("Save")
        delete_button = QPushButton("Delete")
        use_current = QPushButton("Use Current Queue")
        buttons.addWidget(new_button)
        buttons.addWidget(save_button)
        buttons.addWidget(delete_button)
        buttons.addWidget(use_current)
        buttons.addStretch(1)
        layout.addLayout(buttons)
        current_id: list[int | None] = [None]

        def refresh() -> None:
            rows = self.feature_store.list_schedules()
            account_names = {
                int(record["id"]): str(record["name"])
                for record in self.feature_store.list_accounts()
            }
            table.setRowCount(len(rows))
            for row_index, record in enumerate(rows):
                next_text = format_schedule_timestamp(record.get("next_run_at"))
                if record.get("account_profile_id"):
                    account_name = account_names.get(
                        int(record["account_profile_id"]),
                        "Missing profile",
                    )
                else:
                    account_name = "None"
                values = [record["id"], "Yes" if record["enabled"] else "No", record["name"], record["frequency"], next_text, account_name, len(str(record["command_text"]).splitlines())]
                for column, value in enumerate(values):
                    table.setItem(row_index, column, QTableWidgetItem(str(value)))

        def clear_form() -> None:
            current_id[0] = None
            name.setText("Daily archive check")
            account.setCurrentIndex(0)
            commands.setPlainText(self.txt_commands.toPlainText())

        def load_selected() -> None:
            if table.currentRow() < 0:
                return
            item_id = int(table.item(table.currentRow(), 0).text())
            record = next((item for item in self.feature_store.list_schedules() if int(item["id"]) == item_id), None)
            if not record:
                return
            current_id[0] = item_id
            name.setText(str(record["name"]))
            frequency.setCurrentText(str(record["frequency"]))
            interval.setValue(int(record["interval_minutes"]))
            parsed_time = QTime.fromString(str(record["time_of_day"]), "HH:mm")
            if parsed_time.isValid():
                run_time.setTime(parsed_time)
            weekdays.setText(str(record["weekdays"]))
            enabled.setChecked(bool(record["enabled"]))
            account_index = account.findData(record.get("account_profile_id"))
            account.setCurrentIndex(max(0, account_index))
            commands.setPlainText(str(record["command_text"]))

        def save() -> None:
            raw_commands = commands.toPlainText()
            if not raw_commands.strip():
                QMessageBox.warning(page, "Schedule", "The schedule queue cannot be empty.")
                return
            safe_commands = redact_sensitive_database_text(raw_commands)
            if safe_commands != raw_commands:
                answer = QMessageBox.question(
                    page,
                    "Schedule credentials removed",
                    "Inline credentials cannot be stored in a schedule. They will be replaced "
                    "with a redacted placeholder and the schedule will be saved disabled. "
                    "Remove the inline credential, then use an Account profile, cookies, or "
                    "config authentication before enabling it. Save it anyway?",
                )
                if answer != QMessageBox.Yes:
                    return
                commands.setPlainText(safe_commands)
            values: dict[str, object] = {
                "name": name.text(), "command_text": safe_commands,
                "frequency": frequency.currentText(), "interval_minutes": interval.value(),
                "time_of_day": run_time.time().toString("HH:mm"), "weekdays": weekdays.text(),
                "enabled": enabled.isChecked(),
                "account_profile_id": account.currentData(),
            }
            try:
                values["next_run_at"] = next_schedule_time(values)
                current_id[0] = self.feature_store.save_schedule(values, current_id[0])
            except (OSError, ValueError) as exc:
                QMessageBox.warning(page, "Schedule", redact_sensitive_text(str(exc)))
                return
            refresh()

        def delete() -> None:
            if current_id[0]:
                self.feature_store.delete_schedules([current_id[0]])
                clear_form()
                refresh()

        table.itemSelectionChanged.connect(load_selected)
        new_button.clicked.connect(clear_form)
        save_button.clicked.connect(save)
        delete_button.clicked.connect(delete)
        use_current.clicked.connect(lambda: commands.setPlainText(self.txt_commands.toPlainText()))
        refresh()
        return page

    # ----------------------------------------------------------------------- inbox
    def _build_inbox_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        card = QFrame()
        card.setObjectName("card")
        form = QFormLayout(card)
        enabled = QCheckBox("Monitor clipboard and add new HTTP(S) URLs to the queue")
        enabled.setChecked(self.clipboard_inbox_enabled)
        hosts = QLineEdit(self.clipboard_allowed_hosts)
        hosts.setPlaceholderText("Optional: pixiv.net, x.com, instagram.com")
        close_to_tray = QCheckBox("Keep application running in the system tray when the window is closed")
        close_to_tray.setChecked(self.close_to_tray)
        form.addRow(enabled)
        form.addRow("Allowed hosts", hosts)
        form.addRow(close_to_tray)
        layout.addWidget(card)
        note = QLabel(
            "Clipboard Inbox is opt-in, accepts at most 50 URLs per clipboard change, rejects URLs containing embedded credentials, "
            "and can be restricted to an allowlist. It does not start downloads automatically."
        )
        note.setWordWrap(True)
        layout.addWidget(note)
        save = QPushButton("Save Inbox Settings")
        layout.addWidget(save, 0, Qt.AlignLeft)
        layout.addStretch(1)

        def persist() -> None:
            self.clipboard_inbox_enabled = enabled.isChecked()
            self.clipboard_allowed_hosts = hosts.text().strip()
            self.close_to_tray = close_to_tray.isChecked()
            if self.close_to_tray:
                self._ensure_persistent_tray()
            elif self.tray_icon is not None and self.active_workers <= 0:
                self.tray_icon.hide()
            self.autosave_session()
            self.statusBar().showMessage("Inbox settings saved", 3000)

        save.clicked.connect(persist)
        return page

    # -------------------------------------------------------------------- accounts
    def _build_accounts_tab(self) -> QWidget:
        page = QWidget()
        outer = QVBoxLayout(page)
        outer.setContentsMargins(0, 0, 0, 0)
        account_scroll = QScrollArea()
        account_scroll.setObjectName("accountScrollArea")
        account_scroll.setWidgetResizable(True)
        account_scroll.setFrameShape(QFrame.NoFrame)
        account_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        content = QWidget()
        content.setObjectName("accountScrollContent")
        layout = QVBoxLayout(content)
        account_scroll.setWidget(content)
        outer.addWidget(account_scroll)
        platform_backend = self.secret_vault.backend_name
        if os.name == "nt" and platform_backend == "System keyring":
            platform_backend += " (Windows Credential Manager)"
        backend = QLabel(
            "<b>Account profiles</b> keep login settings reusable and scoped to one "
            "gallery-dl site. <b>Secret</b> simply means a password, API key, or token. "
            f"Those values are stored by {platform_backend}; the library database stores "
            "only a random reference. A temporary protected config is created only while "
            "a download runs. OAuth sessions use a separate private cache per profile."
        )
        backend.setWordWrap(True)
        backend.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        layout.addWidget(backend)

        table = self._table(["ID", "Active", "Profile", "Site", "Login method", "Account / source"])
        table.setObjectName("accountProfilesTable")
        table.setMaximumHeight(210)
        layout.addWidget(table)

        site_definitions = {
            str(item.get("key") or "").strip().lower(): str(item.get("name") or "").strip()
            for item in self.gallery_dl_site_preset_definitions()
            if str(item.get("key") or "").strip()
        }
        site_catalog = sorted(set(installed_extractor_categories()) | set(site_definitions))

        form = QGridLayout()
        name = QLineEdit()
        name.setObjectName("accountName")
        name.setPlaceholderText("Optional — generated from site and login method")
        site = QComboBox()
        site.setObjectName("accountSiteCombo")
        site.setEditable(True)
        site.setInsertPolicy(QComboBox.NoInsert)
        site.setMaxVisibleItems(24)
        site.lineEdit().setPlaceholderText("Choose an installed site / extractor")
        for category in site_catalog:
            friendly = site_definitions.get(category)
            site.addItem(f"{friendly} ({category})" if friendly else category, category)
        if site.completer() is not None:
            site.completer().setCaseSensitivity(Qt.CaseInsensitive)
            site.completer().setFilterMode(Qt.MatchContains)
        kind = QComboBox()
        kind.setObjectName("accountMethodCombo")
        kind.addItem("Browser cookies", "browser")
        kind.addItem("cookies.txt", "cookies_file")
        kind.addItem("Username + password", "username_password")
        kind.addItem("API key / token", "api_key")
        kind.addItem("OAuth — connect in browser", "oauth")
        form.addWidget(QLabel("Profile name"), 0, 0)
        form.addWidget(name, 0, 1)
        form.addWidget(QLabel("Site / extractor"), 0, 2)
        form.addWidget(site, 0, 3)
        form.addWidget(QLabel("Login method"), 1, 0)
        form.addWidget(kind, 1, 1)
        method_help = QLabel()
        method_help.setObjectName("accountMethodHelp")
        method_help.setWordWrap(True)
        form.addWidget(method_help, 1, 2, 1, 2)
        form.setColumnStretch(1, 1)
        form.setColumnStretch(3, 1)
        layout.addLayout(form)

        method_stack = QStackedWidget()
        method_stack.setObjectName("accountMethodStack")

        browser_page = QWidget()
        browser_form = QGridLayout(browser_page)
        browser = QComboBox()
        browser.setObjectName("accountBrowser")
        browser.addItems(["chrome", "edge", "firefox", "brave", "chromium", "opera", "vivaldi", "safari"])
        browser_profile = QLineEdit()
        browser_profile.setPlaceholderText("Optional browser profile, e.g. Profile 2")
        browser_domain = QLineEdit()
        browser_domain.setPlaceholderText("Optional domain, e.g. .twitter.com")
        browser_form.addWidget(QLabel("Browser where you are logged in"), 0, 0)
        browser_form.addWidget(browser, 0, 1)
        browser_form.addWidget(QLabel("Profile"), 1, 0)
        browser_form.addWidget(browser_profile, 1, 1)
        browser_form.addWidget(QLabel("Limit to domain"), 2, 0)
        browser_form.addWidget(browser_domain, 2, 1)
        browser_note = QLabel(
            "Recommended for most sites. Login normally in the browser first. "
            "On Windows, close Chrome/Edge if their cookie database is locked."
        )
        browser_note.setWordWrap(True)
        browser_form.addWidget(browser_note, 3, 0, 1, 2)
        browser_form.setColumnStretch(1, 1)
        method_stack.addWidget(browser_page)

        file_page = QWidget()
        file_form = QGridLayout(file_page)
        cookie_file = QLineEdit()
        cookie_file.setObjectName("accountCookieFile")
        cookie_file.setPlaceholderText("Mozilla/Netscape cookies.txt — not JSON")
        choose_cookie_file = QPushButton("Browse…")
        file_form.addWidget(QLabel("cookies.txt file"), 0, 0)
        file_form.addWidget(cookie_file, 0, 1)
        file_form.addWidget(choose_cookie_file, 0, 2)
        file_note = QLabel(
            "This file contains login cookies in plain text. Keep it private and never "
            "upload it or place it in a shared project folder."
        )
        file_note.setWordWrap(True)
        file_form.addWidget(file_note, 1, 0, 1, 3)
        file_form.setColumnStretch(1, 1)
        method_stack.addWidget(file_page)

        password_page = QWidget()
        password_form = QGridLayout(password_page)
        username = QLineEdit()
        username.setObjectName("accountUsername")
        password = QLineEdit()
        password.setObjectName("accountPassword")
        password.setEchoMode(QLineEdit.Password)
        password.setPlaceholderText("Enter password; leave blank when editing to keep it")
        show_password = QCheckBox("Show password")
        password_form.addWidget(QLabel("Username"), 0, 0)
        password_form.addWidget(username, 0, 1)
        password_form.addWidget(QLabel("Password"), 1, 0)
        password_form.addWidget(password, 1, 1)
        password_form.addWidget(show_password, 2, 1)
        password_note = QLabel(
            "Supported directly by gallery-dl for sites such as Nijie, Danbooru, E621, "
            "MangaDex, Sankaku, SubscribeStar, Tapas, and Zerochan. The password is never "
            "shown in commands, logs, exports, or the account database."
        )
        password_note.setWordWrap(True)
        password_form.addWidget(password_note, 3, 0, 1, 2)
        password_form.setColumnStretch(1, 1)
        method_stack.addWidget(password_page)

        api_page = QWidget()
        api_form = QGridLayout(api_page)
        api_username = QLineEdit()
        api_username.setPlaceholderText("Optional account name / user ID")
        secret_key = QComboBox()
        secret_key.setEditable(True)
        secret_key.addItems(["api-key", "token", "access-token", "refresh-token", "client-secret", "password"])
        api_secret = QLineEdit()
        api_secret.setObjectName("accountApiSecret")
        api_secret.setEchoMode(QLineEdit.Password)
        api_secret.setPlaceholderText("Enter key/token; leave blank when editing to keep it")
        show_api_secret = QCheckBox("Show API key / token")
        api_form.addWidget(QLabel("Username / user ID"), 0, 0)
        api_form.addWidget(api_username, 0, 1)
        api_form.addWidget(QLabel("gallery-dl config option"), 1, 0)
        api_form.addWidget(secret_key, 1, 1)
        api_form.addWidget(QLabel("API key / token"), 2, 0)
        api_form.addWidget(api_secret, 2, 1)
        api_form.addWidget(show_api_secret, 3, 1)
        api_note = QLabel(
            "Advanced method: choose the exact option documented for that extractor. "
            "For Danbooru/E621-style sites the API key is commonly supplied as password."
        )
        api_note.setWordWrap(True)
        api_form.addWidget(api_note, 4, 0, 1, 2)
        api_form.setColumnStretch(1, 1)
        method_stack.addWidget(api_page)

        oauth_page = QWidget()
        oauth_form = QGridLayout(oauth_page)
        oauth_instance = QLineEdit()
        oauth_instance.setObjectName("accountOAuthInstance")
        oauth_instance.setPlaceholderText("Required only for Mastodon, e.g. mastodon.social")
        oauth_response = QLineEdit()
        oauth_response.setObjectName("accountOAuthResponse")
        oauth_response.setEchoMode(QLineEdit.Password)
        oauth_response.setPlaceholderText("Paste Pixiv code or a complete OAuth callback URL")
        send_oauth_response = QPushButton("Send response")
        send_oauth_response.setObjectName("accountOAuthSend")
        send_oauth_response.setEnabled(False)
        oauth_form.addWidget(QLabel("Mastodon instance"), 0, 0)
        oauth_form.addWidget(oauth_instance, 0, 1)
        oauth_form.addWidget(QLabel("Authorization response"), 1, 0)
        oauth_form.addWidget(oauth_response, 1, 1)
        oauth_form.addWidget(send_oauth_response, 1, 2)
        oauth_note = QLabel(
            "OAuth opens the site's official authorization page. It is required for Pixiv "
            "and available for DeviantArt, Flickr, Reddit, SmugMug, Tumblr, and Mastodon. "
            "No username/password is entered here; received sessions or tokens stay in this "
            "profile's private cache."
        )
        oauth_note.setWordWrap(True)
        oauth_form.addWidget(oauth_note, 2, 0, 1, 3)
        oauth_form.setColumnStretch(1, 1)
        method_stack.addWidget(oauth_page)
        layout.addWidget(method_stack)

        cache_row = QGridLayout()
        cache_file = QLineEdit()
        cache_file.setObjectName("accountCachePath")
        cache_file.setReadOnly(True)
        cache_file.setPlaceholderText("A private cache path is generated when the profile is saved")
        new_cache = QPushButton("Use new private cache")
        cache_explanation = QLabel(
            "Private cache: gallery-dl stores reusable login sessions and OAuth tokens here. "
            "It is separate for every profile and may contain sensitive account access data."
        )
        cache_explanation.setWordWrap(True)
        cache_row.addWidget(QLabel("Private cache"), 0, 0)
        cache_row.addWidget(cache_file, 0, 1)
        cache_row.addWidget(new_cache, 0, 2)
        cache_row.addWidget(cache_explanation, 1, 0, 1, 3)
        cache_row.setColumnStretch(1, 1)
        layout.addLayout(cache_row)

        process_output = QPlainTextEdit()
        process_output.setObjectName("accountProcessOutput")
        process_output.setReadOnly(True)
        process_output.setMaximumHeight(130)
        process_output.setPlaceholderText("OAuth and cache status messages appear here.")
        layout.addWidget(process_output)

        buttons = QGridLayout()
        new_button = QPushButton("New")
        new_button.setObjectName("accountNewButton")
        save_button = QPushButton("Save Profile")
        save_button.setObjectName("accountSaveButton")
        activate_button = QPushButton("Use Selected")
        activate_button.setObjectName("accountUseButton")
        oauth_button = QPushButton("Connect OAuth")
        oauth_button.setObjectName("accountOAuthButton")
        stop_button = QPushButton("Stop")
        stop_button.setEnabled(False)
        cache_button = QPushButton("Cache Tools")
        cache_button.setObjectName("accountCacheButton")
        clear_site_cache = QPushButton("Clear Site Cache")
        clear_site_cache.setObjectName("accountClearSiteCacheButton")
        clear_secret_button = QPushButton("Forget Password / Token")
        clear_secret_button.setObjectName("accountForgetSecretButton")
        delete_button = QPushButton("Delete")
        delete_button.setObjectName("accountDeleteButton")
        buttons.addWidget(new_button, 0, 0)
        buttons.addWidget(save_button, 0, 1)
        buttons.addWidget(activate_button, 0, 2)
        buttons.addWidget(delete_button, 0, 3)
        buttons.addWidget(oauth_button, 1, 0)
        buttons.addWidget(stop_button, 1, 1)
        buttons.addWidget(cache_button, 1, 2)
        buttons.addWidget(clear_site_cache, 1, 3)
        buttons.addWidget(clear_secret_button, 1, 4)
        buttons.setColumnStretch(5, 1)
        layout.addLayout(buttons)
        layout.addStretch(1)
        current_id: list[int | None] = [None]
        current_ref: list[str] = [""]
        current_cache: list[str] = [""]
        process_action: list[str] = [""]
        process_oauth_site = [""]
        oauth_stream = [OAuthOutputRedactor()]

        process = QProcess(page)
        process.setProcessChannelMode(QProcess.MergedChannels)
        oauth_network = QNetworkAccessManager(page)
        oauth_network.setProxy(QNetworkProxy(QNetworkProxy.NoProxy))

        def selected_site() -> str:
            index = site.currentIndex()
            if index >= 0 and site.currentText() == site.itemText(index):
                return str(site.itemData(index) or "").strip().lower()
            text = site.currentText().strip().lower()
            match = re.search(r"\(([^()]+)\)\s*$", text)
            return (match.group(1) if match else text).strip().lower()

        def select_site(category: str) -> None:
            value = str(category or "").strip().lower()
            index = site.findData(value)
            if index < 0 and value:
                site.addItem(value, value)
                index = site.count() - 1
            site.setCurrentIndex(max(0, index))

        def populate_sites(auth_kind: str, preserve: str = "") -> None:
            if auth_kind == "oauth":
                categories = list(OAUTH_SITES)
            elif auth_kind == "username_password":
                categories = list(USERNAME_PASSWORD_SITES)
            else:
                categories = site_catalog
            wanted = str(preserve or selected_site()).strip().lower()
            site.blockSignals(True)
            try:
                site.clear()
                for category in categories:
                    friendly = site_definitions.get(category)
                    site.addItem(
                        f"{friendly} ({category})" if friendly else category,
                        category,
                    )
                if wanted in categories:
                    select_site(wanted)
                elif site.count():
                    site.setCurrentIndex(0)
            finally:
                site.blockSignals(False)

        def refresh() -> None:
            rows = self.feature_store.list_accounts()
            table.setRowCount(len(rows))
            for row_index, record in enumerate(rows):
                auth_kind = str(record["auth_kind"])
                if auth_kind in {"browser", "cookies_file"}:
                    detail = record["cookie_source"]
                elif auth_kind == "oauth":
                    detail = record.get("oauth_instance") or "Browser authorization"
                else:
                    detail = record["username"] or "Stored securely"
                values = [
                    record["id"],
                    "Yes" if int(record["id"]) == self.active_account_profile_id else "",
                    record["name"],
                    record["site"],
                    ACCOUNT_AUTH_LABELS.get(auth_kind, auth_kind),
                    detail,
                ]
                for column, value in enumerate(values):
                    table.setItem(row_index, column, QTableWidgetItem(str(value)))

        def clear_form() -> None:
            current_id[0] = None
            current_ref[0] = ""
            current_cache[0] = ""
            for field in (
                name,
                browser_profile,
                browser_domain,
                cookie_file,
                username,
                password,
                api_username,
                api_secret,
                oauth_instance,
                oauth_response,
                cache_file,
            ):
                field.clear()
            if site.count():
                select_site("pixiv")
            browser.setCurrentText("chrome")
            secret_key.setCurrentText("api-key")
            kind.setCurrentIndex(0)
            process_output.clear()

        def load_selected() -> None:
            if table.currentRow() < 0:
                return
            account_id = int(table.item(table.currentRow(), 0).text())
            record = self.feature_store.account(account_id)
            if not record:
                return
            current_id[0] = account_id
            current_ref[0] = str(record["secret_ref"])
            current_cache[0] = str(record.get("cache_file") or "")
            name.setText(str(record["name"]))
            kind.setCurrentIndex(max(0, kind.findData(str(record["auth_kind"]))))
            # Preserve legacy/custom profiles even if a newer gallery-dl no
            # longer lists that category; new entries still use the validated
            # installed/documented choices.
            select_site(str(record["site"]))
            browser_name, profile_name, domain_name = split_browser_cookie_source(
                str(record["cookie_source"])
            )
            if browser.findText(browser_name) < 0 and browser_name:
                browser.addItem(browser_name)
            if browser_name:
                browser.setCurrentText(browser_name)
            browser_profile.setText(profile_name)
            browser_domain.setText(domain_name)
            cookie_file.setText(
                str(record["cookie_source"])
                if str(record["auth_kind"]) == "cookies_file"
                else ""
            )
            username.setText(str(record["username"]))
            api_username.setText(str(record["username"]))
            secret_key.setCurrentText(str(record["secret_key"] or "api-key"))
            password.clear()
            api_secret.clear()
            oauth_instance.setText(str(record.get("oauth_instance") or ""))
            oauth_response.clear()
            cache_file.setText(current_cache[0])

        def save() -> bool:
            auth_kind = str(kind.currentData())
            category = selected_site()
            site_problem = account_site_error(category, site_catalog)
            if site_problem:
                QMessageBox.warning(page, "Account profile", site_problem)
                return False
            needs_secret = auth_kind in {"username_password", "api_key"}
            if auth_kind == "username_password" and category not in USERNAME_PASSWORD_SITES:
                answer = QMessageBox.question(
                    page,
                    "Username/password support",
                    f"gallery-dl does not document direct username/password login for {category}. "
                    "Browser cookies are usually more reliable. Save this advanced profile anyway?",
                )
                if answer != QMessageBox.Yes:
                    return False
            if auth_kind == "oauth":
                try:
                    oauth_target(category, oauth_instance.text())
                except ValueError as exc:
                    QMessageBox.warning(page, "OAuth", str(exc))
                    return False
            if auth_kind == "cookies_file":
                path = Path(cookie_file.text().strip()).expanduser()
                valid, message = validate_cookies_txt(str(path))
                if not valid:
                    QMessageBox.warning(page, "cookies.txt", message)
                    return False
            if auth_kind == "username_password" and not username.text().strip():
                QMessageBox.warning(page, "Account profile", "Username is required for this login method.")
                return False
            entered_secret = password.text() if auth_kind == "username_password" else api_secret.text()
            old_reference = current_ref[0]
            reference = old_reference if needs_secret else ""
            previous_secret: str | None = None
            wrote_secret = False
            if needs_secret and entered_secret:
                if not self.secret_vault.available:
                    QMessageBox.warning(page, "Secure storage unavailable", "No OS-protected secret storage is available on this computer.")
                    return False
                reference = reference or self.secret_vault.new_reference()
                try:
                    if old_reference and reference == old_reference:
                        previous_secret = self.secret_vault.get(old_reference)
                    self.secret_vault.set(reference, entered_secret)
                    wrote_secret = True
                except Exception as exc:
                    QMessageBox.warning(
                        page,
                        "Secure storage unavailable",
                        redact_sensitive_text(str(exc)),
                    )
                    return False
            if needs_secret and not reference:
                field_name = "password" if auth_kind == "username_password" else "API key / token"
                QMessageBox.warning(page, "Account profile", f"Enter the {field_name}.")
                return False
            cache_path = current_cache[0] or cache_file.text().strip() or default_account_cache_path(category)
            profile_name = name.text().strip() or f"{category} — {ACCOUNT_AUTH_LABELS[auth_kind]}"
            if auth_kind == "browser":
                try:
                    cookie_source = browser_cookie_source(
                        browser.currentText(),
                        browser_profile.text(),
                        browser_domain.text(),
                    )
                except ValueError as exc:
                    QMessageBox.warning(page, "Browser cookies", str(exc))
                    return False
            elif auth_kind == "cookies_file":
                cookie_source = str(Path(cookie_file.text().strip()).expanduser())
            else:
                cookie_source = ""
            values = {
                "name": profile_name,
                "site": category,
                "auth_kind": auth_kind,
                "username": username.text().strip() if auth_kind == "username_password" else api_username.text().strip() if auth_kind == "api_key" else "",
                "cookie_source": cookie_source,
                "secret_key": "password" if auth_kind == "username_password" else secret_key.currentText().strip() or "api-key",
                "secret_ref": reference,
                "oauth_instance": oauth_instance.text().strip() if auth_kind == "oauth" else "",
                "cache_file": cache_path,
            }
            try:
                current_id[0] = self.feature_store.save_account(values, current_id[0])
            except Exception as exc:
                if wrote_secret:
                    try:
                        if old_reference and reference == old_reference and previous_secret is not None:
                            self.secret_vault.set(old_reference, previous_secret)
                        elif reference != old_reference:
                            self.secret_vault.delete(reference)
                    except Exception:
                        pass
                QMessageBox.warning(
                    page,
                    "Account profile",
                    redact_sensitive_text(str(exc)),
                )
                return False
            if old_reference and not needs_secret:
                try:
                    self.secret_vault.delete(old_reference)
                except Exception as exc:
                    QMessageBox.warning(
                        page,
                        "Account profile",
                        "The profile was saved, but its old secret could not be removed: "
                        f"{redact_sensitive_text(str(exc))}",
                    )
            current_ref[0] = reference
            current_cache[0] = cache_path
            name.setText(profile_name)
            cache_file.setText(cache_path)
            password.clear()
            api_secret.clear()
            refresh()
            return True

        def activate() -> None:
            if current_id[0]:
                record = self.feature_store.account(current_id[0])
                if not record:
                    return
                auth_kind = str(record.get("auth_kind") or "")
                if auth_kind in {"username_password", "api_key"}:
                    try:
                        available = bool(self.secret_vault.get(str(record.get("secret_ref") or "")))
                    except Exception as exc:
                        QMessageBox.warning(page, "Secure storage", redact_sensitive_text(str(exc)))
                        return
                    if not available:
                        QMessageBox.warning(page, "Account profile", "This profile has no stored password/token. Enter it and save first.")
                        return
                if auth_kind == "oauth" and not Path(str(record.get("cache_file") or "")).is_file():
                    QMessageBox.warning(page, "OAuth", "Connect OAuth first; this profile does not have an OAuth cache yet.")
                    return
                self.active_account_profile_id = current_id[0]
                self.autosave_session()
                refresh()

        def append_process_output(text: str) -> None:
            safe = redact_sensitive_text(text)
            process_output.moveCursor(QTextCursor.End)
            process_output.insertPlainText(safe)
            process_output.ensureCursorVisible()

        def read_process_output() -> None:
            data = bytes(process.readAllStandardOutput()).decode("utf-8", errors="replace")
            if data:
                if process_action[0] == "OAuth":
                    append_process_output(oauth_stream[0].feed(data))
                else:
                    append_process_output(data)

        def process_finished(exit_code: int, _status) -> None:
            read_process_output()
            if process_action[0] == "OAuth":
                append_process_output(oauth_stream[0].finish())
            oauth_button.setEnabled(True)
            stop_button.setEnabled(False)
            send_oauth_response.setEnabled(False)
            process_oauth_site[0] = ""
            label = process_action[0] or "Account action"
            append_process_output(f"\n{label} finished with exit code {exit_code}.\n")
            refresh()

        def process_error(_error) -> None:
            if process_action[0] == "OAuth":
                append_process_output(oauth_stream[0].finish())
            oauth_button.setEnabled(True)
            stop_button.setEnabled(False)
            send_oauth_response.setEnabled(False)
            process_oauth_site[0] = ""
            append_process_output("\nCould not start gallery-dl: " + process.errorString() + "\n")

        def run_account_action(action: str) -> None:
            if process.state() != QProcess.NotRunning:
                QMessageBox.information(page, "Account action", "Another OAuth/cache action is still running.")
                return
            if not current_id[0] and not save():
                return
            record = self.feature_store.account(current_id[0])
            if not record:
                return
            if action == "oauth" and str(record.get("auth_kind")) != "oauth":
                QMessageBox.warning(page, "OAuth", "Choose OAuth as the login method and save the profile first.")
                return
            if action in {"clear_site", "clear_all"}:
                scope_text = str(record["site"]) if action == "clear_site" else "everything in this profile's private cache"
                answer = QMessageBox.question(
                    page,
                    "Clear account cache",
                    f"Clear {scope_text}? You may need to log in or connect OAuth again.",
                )
                if answer != QMessageBox.Yes:
                    return
            try:
                cache_path = str(record.get("cache_file") or "")
                Path(cache_path).parent.mkdir(parents=True, exist_ok=True)
                config_path = str(self.config_path or "")
                if config_path and not Path(config_path).expanduser().is_file():
                    config_path = ""
                argv = account_action_argv(
                    self.gdl_cmd or "gallery-dl",
                    action,
                    site=str(record["site"]),
                    cache_file=cache_path,
                    oauth_instance=str(record.get("oauth_instance") or ""),
                    config_path=config_path,
                )
            except (OSError, ValueError) as exc:
                QMessageBox.warning(page, "Account action", str(exc))
                return
            process_action[0] = {
                "oauth": "OAuth",
                "status": "Cache check",
                "clear_site": "Site cache cleanup",
                "clear_all": "Profile cache cleanup",
                "clear_expired": "Expired cache cleanup",
                "vacuum": "Cache optimization",
            }.get(action, action)
            process_oauth_site[0] = str(record["site"]) if action == "oauth" else ""
            oauth_stream[0] = OAuthOutputRedactor()
            process_output.clear()
            if action == "oauth":
                append_process_output(
                    "Starting gallery-dl OAuth. Complete authorization in the browser that opens.\n"
                    "Do not share authorization codes or token output.\n\n"
                )
                append_process_output(oauth_flow_guidance(str(record["site"])) + "\n\n")
                send_oauth_response.setEnabled(True)
            else:
                append_process_output(process_action[0] + "…\n\n")
            oauth_button.setEnabled(False)
            stop_button.setEnabled(True)
            process.setProgram(argv[0])
            process.setArguments(argv[1:])
            process.start()

        def submit_oauth_response() -> None:
            value = oauth_response.text().strip()
            if (
                not value
                or process.state() == QProcess.NotRunning
                or process_action[0] != "OAuth"
            ):
                return
            category = process_oauth_site[0]
            if category == "pixiv":
                process.write((value + "\n").encode("utf-8"))
                oauth_response.clear()
                append_process_output("Pixiv code sent to gallery-dl.\n")
                return
            try:
                callback = local_oauth_callback_url(category, value)
            except ValueError as exc:
                append_process_output(str(exc) + "\n")
                return
            oauth_response.clear()
            reply = oauth_network.get(QNetworkRequest(QUrl(callback)))

            def callback_finished() -> None:
                if reply.error() != QNetworkReply.NoError:
                    append_process_output("Local callback could not be delivered. Check that OAuth is still waiting.\n")
                else:
                    append_process_output("Local callback delivered to gallery-dl.\n")
                reply.deleteLater()

            reply.finished.connect(callback_finished)

        def use_new_cache() -> None:
            category = selected_site() or "account"
            if current_cache[0] and Path(current_cache[0]).is_file():
                answer = QMessageBox.question(
                    page,
                    "Use a new private cache",
                    "The old cache will remain on disk until you clear or delete it. Continue?",
                )
                if answer != QMessageBox.Yes:
                    return
            current_cache[0] = default_account_cache_path(category)
            cache_file.setText(current_cache[0])

        def browse_cookie() -> None:
            chosen, _ = QFileDialog.getOpenFileName(
                page,
                "Choose cookies.txt",
                cookie_file.text(),
                "Cookies (*.txt);;All files (*.*)",
            )
            if chosen:
                cookie_file.setText(chosen)

        def forget_secret() -> None:
            if not current_id[0] or not current_ref[0]:
                QMessageBox.information(page, "Stored credential", "This profile has no stored password or token.")
                return
            if QMessageBox.question(
                page,
                "Forget stored credential",
                "Remove the stored password/API token? The profile will not work until a new value is saved.",
            ) != QMessageBox.Yes:
                return
            old_reference = current_ref[0]
            record = self.feature_store.account(current_id[0]) or {}
            try:
                record["secret_ref"] = ""
                self.feature_store.save_account(record, current_id[0])
                self.secret_vault.delete(old_reference)
            except Exception as exc:
                # If the vault deletion failed, it still contains the secret;
                # restore the metadata reference so the profile remains usable.
                try:
                    if old_reference:
                        record["secret_ref"] = old_reference
                        self.feature_store.save_account(record, current_id[0])
                except Exception:
                    pass
                QMessageBox.warning(page, "Stored credential", redact_sensitive_text(str(exc)))
                return
            current_ref[0] = ""
            password.clear()
            api_secret.clear()
            QMessageBox.information(page, "Stored credential", "The stored password/token was removed.")

        def delete() -> None:
            if not current_id[0]:
                return
            if QMessageBox.question(
                page,
                "Delete account profile",
                "Delete this profile, its stored password/token, and its managed private cache?",
            ) != QMessageBox.Yes:
                return
            cache_path = current_cache[0]
            references = self.feature_store.delete_accounts([current_id[0]])
            cleanup_errors: list[str] = []
            for reference in references:
                try:
                    self.secret_vault.delete(reference)
                except Exception as exc:
                    cleanup_errors.append(redact_sensitive_text(str(exc)))
            if cache_path:
                try:
                    resolved = Path(cache_path).resolve()
                    if resolved.parent == ACCOUNT_CACHE_DIR.resolve():
                        resolved.unlink(missing_ok=True)
                except OSError as exc:
                    cleanup_errors.append(f"Private cache: {redact_sensitive_text(str(exc))}")
            if self.active_account_profile_id == current_id[0]:
                self.active_account_profile_id = None
            clear_form()
            self.autosave_session()
            refresh()
            if cleanup_errors:
                QMessageBox.warning(
                    page,
                    "Account profile",
                    "The profile was deleted, but secure-secret cleanup failed:\n"
                    + "\n".join(cleanup_errors),
                )

        def update_method(*_args) -> None:
            index = max(0, kind.currentIndex())
            method_stack.setCurrentIndex(index)
            auth_kind = str(kind.currentData())
            populate_sites(auth_kind)
            method_help.setText({
                "browser": "Easiest option for most sites; reuses a browser where you already logged in.",
                "cookies_file": "Uses an exported Netscape-format cookies.txt file.",
                "username_password": "Stores username plus password in an OS-protected credential vault.",
                "api_key": "Advanced: stores one API key/token using the extractor's exact config option.",
                "oauth": "Connects through the official site authorization page and an isolated cache.",
            }.get(auth_kind, ""))
            oauth_button.setEnabled(auth_kind == "oauth" and process.state() == QProcess.NotRunning)
            clear_secret_button.setEnabled(auth_kind in {"username_password", "api_key"})
            oauth_instance.setEnabled(auth_kind == "oauth" and selected_site() == "mastodon")
            site_changed()

        def site_changed(*_args) -> None:
            category = selected_site()
            oauth_instance.setEnabled(kind.currentData() == "oauth" and category == "mastodon")
            if kind.currentData() == "oauth":
                send_oauth_response.setText("Send Pixiv Code" if category == "pixiv" else "Send Callback URL")
                oauth_response.setPlaceholderText(
                    "Pixiv code or callback URL" if category == "pixiv" else
                    "Full HTTPS redirect or http://localhost:6414/?... URL"
                )
                try:
                    oauth_note.setText(oauth_flow_guidance(category))
                except ValueError:
                    oauth_note.setText("Select a supported OAuth site to see its instructions.")

        table.itemSelectionChanged.connect(load_selected)
        new_button.clicked.connect(clear_form)
        save_button.clicked.connect(save)
        activate_button.clicked.connect(activate)
        kind.currentIndexChanged.connect(update_method)
        site.currentIndexChanged.connect(site_changed)
        if site.lineEdit() is not None:
            site.lineEdit().textChanged.connect(site_changed)
        show_password.toggled.connect(
            lambda checked: password.setEchoMode(QLineEdit.Normal if checked else QLineEdit.Password)
        )
        show_api_secret.toggled.connect(
            lambda checked: api_secret.setEchoMode(QLineEdit.Normal if checked else QLineEdit.Password)
        )
        choose_cookie_file.clicked.connect(browse_cookie)
        new_cache.clicked.connect(use_new_cache)
        oauth_button.clicked.connect(lambda: run_account_action("oauth"))
        send_oauth_response.clicked.connect(submit_oauth_response)
        oauth_response.returnPressed.connect(submit_oauth_response)
        stop_button.clicked.connect(process.terminate)
        cache_menu = QMenu(cache_button)
        cache_menu.addAction("Check cache status").triggered.connect(
            lambda: run_account_action("status")
        )
        cache_menu.addAction("Clear expired cache entries").triggered.connect(
            lambda: run_account_action("clear_expired")
        )
        cache_menu.addAction("Clear all of this profile's cache").triggered.connect(
            lambda: run_account_action("clear_all")
        )
        cache_menu.addAction("Vacuum / optimize cache").triggered.connect(
            lambda: run_account_action("vacuum")
        )
        cache_button.setMenu(cache_menu)
        clear_site_cache.clicked.connect(lambda: run_account_action("clear_site"))
        clear_secret_button.clicked.connect(forget_secret)
        delete_button.clicked.connect(delete)
        process.readyReadStandardOutput.connect(read_process_output)
        process.finished.connect(process_finished)
        process.errorOccurred.connect(process_error)
        page.destroyed.connect(
            lambda *_args: process.kill() if process.state() != QProcess.NotRunning else None
        )
        clear_form()
        update_method()
        refresh()
        return page

    # -------------------------------------------------------------- options/filters
    def _build_options_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        splitter = QTabWidget()
        layout.addWidget(splitter, 1)

        options_page = QWidget()
        options_layout = QVBoxLayout(options_page)
        search = QLineEdit()
        search.setPlaceholderText("Search installed gallery-dl options")
        table = self._table(["Option", "Value?", "Description"])
        value = QLineEdit()
        value.setPlaceholderText("Value for the selected option")
        apply_button = QPushButton("Apply Selected Option to Current Input")
        options_layout.addWidget(search)
        options_layout.addWidget(table, 1)
        options_layout.addWidget(value)
        options_layout.addWidget(apply_button)
        splitter.addTab(options_page, "Options Catalog")

        # Show the safe fallback immediately and probe the installed version
        # asynchronously. Opening Management must never freeze the GUI for the
        # former eight-second subprocess timeout.
        catalog = parse_help_options("")
        catalog_process = QProcess(page)
        catalog_process.setProcessChannelMode(QProcess.MergedChannels)
        catalog_timeout = QTimer(page)
        catalog_timeout.setSingleShot(True)
        catalog_timeout.timeout.connect(
            lambda: catalog_process.kill()
            if catalog_process.state() != QProcess.NotRunning
            else None
        )

        def refresh_catalog() -> None:
            needle = search.text().strip().lower()
            rows = [item for item in catalog if not needle or needle in item[0].lower() or needle in item[1].lower()]
            table.setRowCount(len(rows))
            for row_index, (flag, description, needs_value) in enumerate(rows):
                table.setItem(row_index, 0, QTableWidgetItem(flag))
                table.setItem(row_index, 1, QTableWidgetItem("Yes" if needs_value else "No"))
                table.setItem(row_index, 2, QTableWidgetItem(description))

        def catalog_finished(_exit_code: int, _exit_status) -> None:
            # The dialog can be closed while ``gallery-dl --help`` is still
            # running. Its page-owned QProcess is then destroyed before the
            # queued ``finished`` signal reaches Python. Never dereference a
            # deleted C++ wrapper from this late callback.
            if not isValid(catalog_process) or not isValid(catalog_timeout):
                return
            catalog_timeout.stop()
            output_text = bytes(catalog_process.readAllStandardOutput()).decode(errors="replace")
            if output_text.strip():
                catalog[:] = parse_help_options(output_text)
                refresh_catalog()

        def apply_option() -> None:
            if self.active_workers > 0:
                QMessageBox.information(page, "Option", "Wait for the current download to finish before changing the queue.")
                return
            row = table.currentRow()
            if row < 0:
                return
            flag = table.item(row, 0).text()
            needs_value = table.item(row, 1).text() == "Yes"
            if needs_value and not value.text().strip():
                QMessageBox.warning(page, "Option", f"{flag} requires a value.")
                return
            extra = flag
            if needs_value:
                extra += " " + quote_arg_for_preview(value.text().strip())
            self.txt_commands.setPlainText(
                append_extra_args_to_database_text(self.txt_commands.toPlainText(), extra)
            )
            if not self._rebuild_from_text():
                return

        search.textChanged.connect(refresh_catalog)
        apply_button.clicked.connect(apply_option)
        refresh_catalog()
        command = command_string_to_argv(self.gdl_cmd or "gallery-dl")
        if command:
            catalog_process.finished.connect(catalog_finished)
            catalog_process.start(command[0], [*command[1:], "--help"])
            catalog_timeout.start(8_000)

        filter_page = QWidget()
        filter_layout = QVBoxLayout(filter_page)
        joiner = QComboBox()
        joiner.addItems(["and", "or"])
        grid = QGridLayout()
        grid.addWidget(QLabel("Metadata field"), 0, 0)
        grid.addWidget(QLabel("Operator"), 0, 1)
        grid.addWidget(QLabel("Value"), 0, 2)
        rule_fields: list[tuple[QLineEdit, QComboBox, QLineEdit]] = []
        defaults = [("extension", "in", '("jpg", "png")'), ("width", ">=", "1920"), ("", "==", "")]
        for index, (field_default, op_default, value_default) in enumerate(defaults, start=1):
            field = QLineEdit(field_default)
            operator = QComboBox()
            operator.addItems(["==", "!=", ">", ">=", "<", "<=", "in", "not in", "contains"])
            operator.setCurrentText(op_default)
            rule_value = QLineEdit(value_default)
            grid.addWidget(field, index, 0)
            grid.addWidget(operator, index, 1)
            grid.addWidget(rule_value, index, 2)
            rule_fields.append((field, operator, rule_value))
        filter_layout.addLayout(grid)
        filter_layout.addWidget(QLabel("Join rules with"))
        filter_layout.addWidget(joiner)
        preview = QLineEdit()
        preview.setReadOnly(True)
        filter_layout.addWidget(QLabel("Expression preview"))
        filter_layout.addWidget(preview)
        filter_buttons = QHBoxLayout()
        build_button = QPushButton("Build")
        copy_button = QPushButton("Copy")
        apply_filter = QPushButton("Apply --filter to Current Input")
        filter_buttons.addWidget(build_button)
        filter_buttons.addWidget(copy_button)
        filter_buttons.addWidget(apply_filter)
        filter_layout.addLayout(filter_buttons)
        filter_layout.addStretch(1)
        splitter.addTab(filter_page, "Visual Filter Builder")

        def build() -> str:
            try:
                expression = build_filter_expression(
                    [(field.text(), operator.currentText(), rule_value.text()) for field, operator, rule_value in rule_fields],
                    joiner.currentText(),
                )
            except ValueError as exc:
                QMessageBox.warning(page, "Filter", redact_sensitive_text(str(exc)))
                return ""
            preview.setText(expression)
            return expression

        def apply_expression() -> None:
            if self.active_workers > 0:
                QMessageBox.information(page, "Filter", "Wait for the current download to finish before changing the queue.")
                return
            expression = build()
            if not expression:
                return
            extra = "--filter " + quote_arg_for_preview(expression)
            self.txt_commands.setPlainText(
                append_extra_args_to_database_text(self.txt_commands.toPlainText(), extra)
            )
            if not self._rebuild_from_text():
                return

        build_button.clicked.connect(build)
        copy_button.clicked.connect(lambda: QApplication.clipboard().setText(build()))
        apply_filter.clicked.connect(apply_expression)
        build()
        return page

    # --------------------------------------------------------------------- runtime
    def _managed_python(self) -> Path:
        return MANAGED_VENV_DIR / ("Scripts/python.exe" if os.name == "nt" else "bin/python")

    def _managed_gallery_dl(self) -> Path:
        return MANAGED_VENV_DIR / ("Scripts/gallery-dl.exe" if os.name == "nt" else "bin/gallery-dl")

    def _build_runtime_tab(self) -> QWidget:
        page = QWidget()
        layout = QVBoxLayout(page)
        frozen = bool(getattr(sys, "frozen", False))
        current = QLabel(f"gallery-dl in use: {self.gdl_cmd or 'not found'}")
        current.setWordWrap(True)
        if frozen:
            note = QLabel(
                "gallery-dl is included with this application. No separate Python runtime or installation is needed. "
                "To update the included gallery-dl, install a newer GdlScrape release."
            )
            note.setWordWrap(True)
            layout.addWidget(note)
            layout.addWidget(current)
            layout.addStretch(1)
            return page
        managed = QLabel(f"Managed runtime: {self._managed_gallery_dl()}")
        managed.setWordWrap(True)
        output = QPlainTextEdit()
        output.setReadOnly(True)
        output.setPlaceholderText("Runtime installation output")
        buttons = QHBoxLayout()
        install = QPushButton("Install / Update Managed Runtime")
        use_managed = QPushButton("Use Managed Runtime")
        buttons.addWidget(install)
        buttons.addWidget(use_managed)
        buttons.addStretch(1)
        layout.addWidget(current)
        layout.addWidget(managed)
        layout.addLayout(buttons)
        layout.addWidget(output, 1)

        def runtime_message(text: str) -> None:
            if not text:
                return
            if isValid(output):
                output.appendPlainText(text)
            else:
                # Runtime installation intentionally survives closing the
                # Management dialog, so keep progress observable in main log.
                self.append_log(f"[runtime] {text}")

        def append_output() -> None:
            process = self._runtime_process
            if process is not None and isValid(process):
                text = bytes(process.readAllStandardOutput()).decode(errors="replace")
                if text:
                    runtime_message(text.rstrip())

        def start_install() -> None:
            if self.active_workers > 0 or (self._runtime_process and self._runtime_process.state() != QProcess.NotRunning):
                self.show_compact_message("Runtime", "Wait for downloads or the current runtime operation to finish.", "info")
                return
            answer = QMessageBox.question(
                page, "Managed Runtime",
                f"Create or update an isolated Python environment at:\n{MANAGED_VENV_DIR}\n\nContinue?",
            )
            if answer != QMessageBox.Yes:
                return
            try:
                SECURE_RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
            except OSError as exc:
                self.show_compact_message(
                    "Managed Runtime",
                    f"Could not prepare the runtime directory:\n{SECURE_RUNTIME_DIR}\n\n{exc}",
                    "error",
                )
                return
            output.clear()
            process = QProcess(self)
            process.setProcessChannelMode(QProcess.MergedChannels)
            process.readyReadStandardOutput.connect(append_output)
            process.finished.connect(finish_stage)
            process.errorOccurred.connect(runtime_error)
            self._runtime_process = process
            if self._managed_python().is_file():
                self._runtime_stage = "install"
                process.start(str(self._managed_python()), ["-m", "pip", "install", "--upgrade", "gallery-dl"])
            else:
                self._runtime_stage = "venv"
                process.start(sys.executable, ["-m", "venv", str(MANAGED_VENV_DIR)])

        def runtime_error(_process_error) -> None:
            process = self._runtime_process
            detail = process.errorString() if process is not None and isValid(process) else "process unavailable"
            runtime_message(f"Runtime operation could not start: {detail}")
            self._runtime_stage = ""

        def finish_stage(exit_code: int, _exit_status) -> None:
            append_output()
            if exit_code != 0:
                runtime_message(f"Runtime operation failed with exit code {exit_code}.")
                self._runtime_stage = ""
                return
            if self._runtime_stage == "venv":
                self._runtime_stage = "install"
                assert self._runtime_process is not None
                self._runtime_process.start(str(self._managed_python()), ["-m", "pip", "install", "--upgrade", "gallery-dl"])
                return
            executable = self._managed_gallery_dl()
            if executable.is_file():
                self.gdl_cmd = str(executable)
                self._refresh_env()
                self.autosave_session()
                if isValid(current):
                    current.setText(f"gallery-dl in use: {self.gdl_cmd}")
                runtime_message("Managed runtime is ready and selected.")
            else:
                runtime_message("Runtime operation finished, but gallery-dl was not created.")
            self._runtime_stage = ""

        def activate_managed() -> None:
            executable = self._managed_gallery_dl()
            if not executable.is_file():
                QMessageBox.warning(page, "Runtime", "Install the managed runtime first.")
                return
            self.gdl_cmd = str(executable)
            self._refresh_env()
            self.autosave_session()
            current.setText(f"gallery-dl in use: {self.gdl_cmd}")

        install.clicked.connect(start_install)
        use_managed.clicked.connect(activate_managed)
        return page


__all__ = [
    "MANAGED_VENV_DIR",
    "ManagementMixin",
    "common_account_profile_id",
    "format_schedule_timestamp",
    "interrupted_recovery_commands",
    "library_records_to_database_text",
]
